[build]
bin = "./tmp/server-binary.exe"
cmd = "go build -o ./tmp/server-binary.exe ./server/*.go"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_ext = ["go", "tpl", "tmpl", "html"]
rerun = false
stop_on_error = false
poll = true

[log]
level = "debug"

[screen]
clear_on_rebuild = false
keep_scroll = true