version: "3.8"

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${LOCAL_DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - art-market-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: art-market-api-prod
    image: ${DOCKERHUB_USERNAME}/art-market-backend:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./path/to/.env:/app/.env # mount host file into container
    depends_on:
      db:
        condition: service_healthy
    networks:
      - art-market-network

networks:
  art-market-network:

volumes:
  postgres_data: