package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/ut-sama-art-studio/art-market-backend/graph/model"
)

// CreateMerch is the resolver for the createMerch field.
func (r *mutationResolver) CreateMerch(ctx context.Context, input model.NewMerch) (*model.MerchItem, error) {
	panic(fmt.Errorf("not implemented: CreateMerch - createMerch"))
}
