// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MerchItem struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Type        *string   `json:"type,omitempty"`
	Description *string   `json:"description,omitempty"`
	Images      []*string `json:"images"`
	Price       float64   `json:"price"`
	Inventory   *int      `json:"inventory,omitempty"`
	Width       *float64  `json:"width,omitempty"`
	Height      *float64  `json:"height,omitempty"`
}

type Mutation struct {
}

type NewMerch struct {
	Name        string    `json:"name"`
	Type        *string   `json:"type,omitempty"`
	Description *string   `json:"description,omitempty"`
	Images      []*string `json:"images"`
	Price       float64   `json:"price"`
	Inventory   *int      `json:"inventory,omitempty"`
	Width       *float64  `json:"width,omitempty"`
	Height      *float64  `json:"height,omitempty"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type UpdateMerch struct {
	ID          string    `json:"id"`
	Name        *string   `json:"name,omitempty"`
	Type        *string   `json:"type,omitempty"`
	Description *string   `json:"description,omitempty"`
	Images      []*string `json:"images,omitempty"`
	Price       *float64  `json:"price,omitempty"`
	Inventory   *int      `json:"inventory,omitempty"`
	Width       *float64  `json:"width,omitempty"`
	Height      *float64  `json:"height,omitempty"`
}

type UpdateUser struct {
	Name           *string `json:"name,omitempty"`
	Email          *string `json:"email,omitempty"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Bio            *string `json:"bio,omitempty"`
}

type User struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Username       *string `json:"username,omitempty"`
	Email          *string `json:"email,omitempty"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Bio            *string `json:"bio,omitempty"`
	Role           *string `json:"role,omitempty"`
}
