// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MerchItem struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Type        *string   `json:"type,omitempty"`
	Description *string   `json:"description,omitempty"`
	Images      []*string `json:"images"`
	Price       float64   `json:"price"`
	Inventory   *int      `json:"inventory,omitempty"`
}

type Mutation struct {
}

type NewMerch struct {
	Name        string    `json:"name"`
	Type        *string   `json:"type,omitempty"`
	Description *string   `json:"description,omitempty"`
	Images      []*string `json:"images"`
	Price       float64   `json:"price"`
	Inventory   *int      `json:"inventory,omitempty"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Bio            *string `json:"bio,omitempty"`
}
