// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type MerchItem struct {
	ID          string    `json:"id"`
	OwnerID     string    `json:"ownerId"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Price       float64   `json:"price"`
	Inventory   *int      `json:"inventory,omitempty"`
	Type        string    `json:"type"`
	Width       *float64  `json:"width,omitempty"`
	Height      *float64  `json:"height,omitempty"`
	Unit        *string   `json:"unit,omitempty"`
	Images      []*string `json:"images"`
}

type Mutation struct {
}

type NewMerch struct {
	Name        string            `json:"name"`
	Description *string           `json:"description,omitempty"`
	Price       float64           `json:"price"`
	Inventory   *int              `json:"inventory,omitempty"`
	Type        string            `json:"type"`
	Width       *float64          `json:"width,omitempty"`
	Height      *float64          `json:"height,omitempty"`
	Unit        *string           `json:"unit,omitempty"`
	Images      []*graphql.Upload `json:"images"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type UpdateMerch struct {
	ID             string            `json:"id"`
	Name           *string           `json:"name,omitempty"`
	Description    *string           `json:"description,omitempty"`
	Price          *float64          `json:"price,omitempty"`
	Inventory      *int              `json:"inventory,omitempty"`
	Type           *string           `json:"type,omitempty"`
	Width          *float64          `json:"width,omitempty"`
	Height         *float64          `json:"height,omitempty"`
	Unit           *string           `json:"unit,omitempty"`
	ReorderedImage []*string         `json:"reorderedImage,omitempty"`
	ImagesToDelete []*string         `json:"imagesToDelete,omitempty"`
	NewImages      []*graphql.Upload `json:"newImages,omitempty"`
}

type UpdateUser struct {
	Name           *string `json:"name,omitempty"`
	Email          *string `json:"email,omitempty"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Bio            *string `json:"bio,omitempty"`
}

type User struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Username       *string `json:"username,omitempty"`
	Email          *string `json:"email,omitempty"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Bio            *string `json:"bio,omitempty"`
	Role           *string `json:"role,omitempty"`
}
