name: Deploy to Digital Ocean on merge
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/art-market-backend:latest
          platforms: linux/amd64

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/art-market-backend
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker-compose down
            docker-compose pull
            docker-compose up -d

      - name: Verify Docker container is running
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Checking running containers..."
            docker ps
            echo "Verifying art-market-api-prod container is running..."
            if docker ps --filter "name=^art-market-api-prod$" --format '{{.Names}}' | grep -q "^art-market-api-prod$"; then
              echo "Success: art-market-api-prod container is running"
            else
              echo "Error: art-market-api-prod container is not running"
              docker ps -a  # Show all containers (including stopped) for debugging
              exit 1
            fi

      - name: Verify server is online
        run: |
          sleep 10
          response=$(curl --silent --write-out "%{http_code}" -o response.txt https://utsama.kevicai.com/api/hello-world)
          if [ "$response" -eq 200 ]; then
            echo "Server is online! Response: $(cat response.txt)"
          else
            echo "Failed to verify server. HTTP Status: $response, Response: $(cat response.txt)"
            exit 1
          fi